version: '2'
services:
    DB:
        image: mariadb:latest
        container_name: DB
        ports:
            - '3306:3306'
        environment:
          MYSQL_USER: app
          MYSQL_PASSWORD: pass
          MYSQL_ROOT_PASSWORD: passr
          MYSQL_DATABASE: comedordb

        volumes:
            - ./db:/var/lib/mysql      

    HTTP:
        image: lokiteitor:laravel
        build:
            context: ./laravel
        volumes:
            - ./../api:/usr/local/apache2/htdocs
            - ./logs/:/var/log/apache2/
            - ./apache/000-default.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
        container_name: HTTP
        links:
            - DB:mysql
        ports:
            - "80:80"
            - 443

    proxy-inverse:
        image: nginx:alpine
        volumes:
            - './nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        container_name: proxy
        links:
            - HTTP:http      